services:
  db:
    image: postgres:15
    container_name: link_saver_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - 5432:5432

  web:
    build: ./
    container_name: link_saver_web
    restart: always
    command: bash entrypoint.sh
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env
    environment:
      - DEBUG=1

volumes:
  postgres_data:
